### ISSUE TITLE
a placeholder for a security issue

### ISSUE THREAD

**Issue by ilatypov** [victorwon/calendarxp#2]
```
Date: Mon, 24 Apr 2017 17:46:39 +0000 (UTC)
From: Ilguiz Latypov <ilatypov@yahoo.ca>
To: "support@calendarxp.net" <support@calendarxp.net>
Subject: Question about FlatCalendarXP - Ref#1493055020520

```

**Comment by victorwon** [comment]
Thanks!

**Comment by ilatypov** [comment]
Luckily, this covered both [JSFuck](https://github.com/aemkei/jsfuck) (because we reject parentheses) and Gareth Heyes's way of [executing code without parentheses](http://blog.portswigger.net/2016/07/executing-non-alphanumeric-javascript.html) (because we reject back-ticks).  Doing away with expecting javascript from externally controlled sources can eradicate the vulnerability.
